version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ${HOME}/images:/images
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: "postgres:16.2-alpine"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    container_name: frontend
    build:
      context: ./frontend

  generator:
    container_name: generator
    build:
      context: ./generator
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  spring-postgres:

volumes:
  postgres_data:
