services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ${HOME}/images:/images
    env_file:
      - .env.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis

  db:
    image: "postgres:16.2-alpine"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:7.4.1-alpine"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file:
      - .env.frontend

  generator:
    container_name: generator
    build:
      context: ./generator
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  spring-postgres:

volumes:
  postgres_data:
  redis_data: