version: "3.8"
services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ${HOME}/images:/images
    ports:
      - 8080:8080
      - 35729:35729
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: "postgres:16.2-alpine"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000

  generator:
    container_name: generator
    build:
      context: ./generator
    ports:
      - 5000:5000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
networks:
  spring-postgres:

volumes:
  postgres_data:
