spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: NicoAi

cors:
  origins: ${FRONTEND_URL}
api:
  image-generator:
    url: ${IMAGE_GENERATOR_URL}

jwt:
  secret: ${JWT_SECRET}
image:
  FOLDER_PATH: ${FOLDER_PATH}
stripe:
  public-key: ${STRIPE_API_PUBLIC_KEY}
  secret-key: ${STRIPE_API_SECRET_KEY}
  webhook-key: ${STRIPE_API_WEBHOOK_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE