spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: NicoAi

cors:
  origins:
    - "http://localhost:3000"
api:
  image-generator:
    url: "https://b4fa-34-136-49-160.ngrok-free.app"
