spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: NicoAi

cors:
  origins: ${FRONTEND_URL}
api:
  image-generator:
    url: ${IMAGE_GENERATOR_URL}

jwt:
  secret: ${JWT_SECRET}
image:
  FOLDER_PATH: ${FOLDER_PATH}

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE

