spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  application:
    name: NicoAi

cors:
  origins: "${FRONTEND_URL}"
api:
  image-generator:
    url: "${IMAGE_GENERATOR_URL}"

jwt:
  secret: ${JWT_SECRET}
